parks/urls.py
from django.conf.urls import *
from django.views.generic import TemplateView


from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<park_id>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<park_id>[0-9]+)/favorite$', views.add_favorite_park, name='favorite'),
    url(r'^(?P<park_id>[0-9]+)/unfavorite$', views.unfavorite_park, name='unfavorite'),
    url(r'^[0-9]+/put_rating/$', views.put_rating),
    url(r'^put_rating/$', views.put_rating),
    url(r'^(?P<park_id>[0-9]+)/problem$', views.submit_problem, name='problem'),
    url(r'^problem_submit/$', TemplateView.as_view(template_name='parks/problem_done.html'), name='problem_done'),
]

parktracker/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
from parks import views
from django.contrib.auth import views as built_in_views
from django.views.generic.base import RedirectView
from . import auth_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='parks', permanent=False), name='home'),
    url(r'^accounts/login/$', RedirectView.as_view(url=reverse_lazy('login'), permanent=False), name='go_to_login'),
    url(r'^parks/', include('parks.urls', namespace="parks")),
    url(r'^admin/', include(admin.site.urls)),
    url('^password-change/', built_in_views.password_change, name='password_change'),
    url('^login/', built_in_views.login, name='login'),
    url(r'^password_reset/$', built_in_views.password_reset, name='password_reset'),
    url(r'^password_reset_done/$', built_in_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset_complete/$', built_in_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', built_in_views.password_reset_confirm, name='password_reset_confirm'),
    url('^logout/', auth_views.logout_view, name='logout'),
    url(r'^create-account/$', auth_views.add_user, name='add_user'),
    url(r'^admin/parse', views.get_data, name='parse'),
    url(r'^admin/clear', views.clear_data, name='clear'),
]

parks/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.contrib.auth.models import User
from .rating import calculate_new_rating
from django.contrib.auth.models import User

class UserRating(models.Model):
    user = models.ForeignKey(User, null=True)
    park = models.ForeignKey('Park')
    rating = models.FloatField()
    class Meta():
        db_table = 'rating_tbl'
    @classmethod
    def create(cls, rating, park, user):
        rats = UserRating.objects.filter(user=user, park=park)
        if (not rats):
            newRating = cls(rating=rating, park=park, user=user)
            newRating.save()
            calculate_new_rating(park, rating, 0)
        else:
            for rat in rats:
                previousRating = rat
            else:
                preRatingFloat = previousRating.rating
                newRating = cls(rating=rating, park=park, user=user)
                previousRating.delete()
                newRating.save()
                calculate_new_rating(park, rating, preRatingFloat)

class Park(models.Model):
    park_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=100)
    official = models.IntegerField()
    address = models.CharField(max_length=100)
    neighbourhood = models.CharField(max_length=100)
    nurl = models.CharField(max_length=100)
    lat = models.FloatField(null=True)
    long = models.FloatField(null=True)
    size = models.FloatField()
    washroom = models.IntegerField(null=True)
    special = models.IntegerField()
    advisory = models.IntegerField()
    problems = models.CharField(max_length=150, null=True)
    rating = models.FloatField()


    nearest1_id = models.IntegerField(null=True)
    nearest1_distance = models.FloatField(null=True)
    nearest1_name = models.CharField(max_length=100, null=True)
    nearest1_image = models.CharField(max_length=100, null=True)

    nearest2_id = models.IntegerField(null=True)
    nearest2_distance = models.FloatField(null=True)
    nearest2_name = models.CharField(max_length=100, null=True)
    nearest2_image = models.CharField(max_length=100, null=True)

    nearest3_id = models.IntegerField(null=True)
    nearest3_distance = models.FloatField(null=True)
    nearest3_name = models.CharField(max_length=100, null=True)
    nearest3_image = models.CharField(max_length=100, null=True)

    nearest4_id = models.IntegerField(null=True)
    nearest4_distance = models.FloatField(null=True)
    nearest4_name = models.CharField(max_length=100, null=True)
    nearest4_image = models.CharField(max_length=100, null=True)

    __callArg = []
    def update_rating(self, rating, user):
        UserRating.create(rating, self, user)

    def __str__(self):
        return self.name
    class Meta():
        db_table = 'parks_tbl'


class ParkFavorites(models.Model):
    user_id = models.IntegerField(primary_key=True)
    def __str__(self):
        return self.name
    class Meta():
        db_table = 'park_favorites_tbl'

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile')
    favorite_park = models.CharField(max_length=1000, null=True)

    def __str__(self):
          return "%s's profile" % self.user

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

@receiver(pre_delete, sender=User)
def delete_profile_for_user(sender, instance=None, **kwargs):
    if instance:
        user_profile = UserProfile.objects.get(user=instance)
        user_profile.delete()

parks/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('favorite_park',)

class ProblemForm(forms.Form):
    description = forms.CharField(max_length=150)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

parks/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views import generic
from django.core.mail import mail_admins
from .newdata import parse, cleardb
from .forms import ProblemForm
from .models import Park
from django.views.decorators.csrf import csrf_exempt
from django.http import QueryDict
import json
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'parks/index.html'
    context_object_name = 'list_of_parks'

    def get_context_data(self, **kwargs):
        context = generic.ListView.get_context_data(self, **kwargs)
        context['favorite'] = self.request.GET.get('favorite', None)
        context['washroom'] = self.request.GET.get('washroom', None)
        context['arbutus_ridge'] = self.request.GET.get('arbutus_ridge', None)
        context['downtown'] = self.request.GET.get('downtown', None)
        context['west_end'] = self.request.GET.get('west_end', None)
        context['dunbar_southlands'] = self.request.GET.get('dunbar_southlands', None)
        context['fairview'] = self.request.GET.get('fairview', None)
        context['grandview_woodland'] = self.request.GET.get('grandview_woodland', None)
        context['hastings_sunrise'] = self.request.GET.get('hastings_sunrise', None)
        context['kensington_cedar_cottage'] = self.request.GET.get('kensington_cedar_cottage', None)
        context['kerrisdale'] = self.request.GET.get('kerrisdale', None)
        context['killarney'] = self.request.GET.get('killarney', None)
        context['west_point_grey'] = self.request.GET.get('west_point_grey', None)
        context['kitsilano'] = self.request.GET.get('kitsilano', None)
        context['marpole'] = self.request.GET.get('marpole', None)
        context['mount_pleasant'] = self.request.GET.get('mount_pleasant', None)
        context['oakridge'] = self.request.GET.get('oakridge', None)
        context['south_cambie'] = self.request.GET.get('south_cambie', None)
        context['renfrew_collingwood'] = self.request.GET.get('renfrew_collingwood', None)
        context['riley_little_mountain'] = self.request.GET.get('riley_little_mountain', None)
        context['shaughnessy'] = self.request.GET.get('shaughnessy', None)
        context['strathcona'] = self.request.GET.get('strathcona', None)
        context['sunset'] = self.request.GET.get('sunset', None)
        context['victoria_fraserview'] = self.request.GET.get('victoria_fraserview', None)
        context['map_select'] = self.request.GET.get('map', None)
        return context

    def get_queryset(self):
        queryset = Park.objects.order_by('name')
        neighbourhoods = []
        favorites = []

        # get the filters from the GET
        request_favorite = self.request.GET.get('favorite', None)
        if request_favorite == 'true':
            favorites = get_favorite_parks(self.request)
        request_washroom = self.request.GET.get('washroom', None)
        if request_washroom == 'true':
            queryset = queryset.filter(washroom=1)
        arbutus_ridge = self.request.GET.get('arbutus_ridge', None)
        if arbutus_ridge == 'true':
            neighbourhoods.append('Arbutus Ridge')
        downtown = self.request.GET.get('downtown', None)
        if downtown == 'true':
            neighbourhoods.append('Downtown')
        west_end = self.request.GET.get('west_end', None)
        if west_end == 'true':
            neighbourhoods.append('West End')
        dunbar_southlands = self.request.GET.get('dunbar_southlands', None)
        if dunbar_southlands == 'true':
            neighbourhoods.append('Dunbar-Southlands')
        fairview = self.request.GET.get('fairview', None)
        if fairview == 'true':
            neighbourhoods.append('Fairview')
        grandview_woodland = self.request.GET.get('grandview_woodland', None)
        if grandview_woodland == 'true':
            neighbourhoods.append('Grandview-Woodland')
        hastings_sunrise = self.request.GET.get('hastings_sunrise', None)
        if hastings_sunrise == 'true':
            neighbourhoods.append('Hastings-Sunrise')
        kensington_cedar_cottage = self.request.GET.get('kensington_cedar_cottage', None)
        if kensington_cedar_cottage == 'true':
            neighbourhoods.append('Kensington-Cedar Cottage')
        kerrisdale = self.request.GET.get('kerrisdale', None)
        if kerrisdale == 'true':
            neighbourhoods.append('Kerrisdale')
        killarney = self.request.GET.get('killarney', None)
        if killarney == 'true':
            neighbourhoods.append('Killarney')
        west_point_grey = self.request.GET.get('west_point_grey', None)
        if west_point_grey == 'true':
            neighbourhoods.append('West Point Grey')
        kitsilano = self.request.GET.get('kitsilano', None)
        if kitsilano == 'true':
            neighbourhoods.append('Kitsilano')
        marpole = self.request.GET.get('marpole', None)
        if marpole == 'true':
            neighbourhoods.append('Marpole')
        mount_pleasant = self.request.GET.get('mount_pleasant', None)
        if mount_pleasant == 'true':
            neighbourhoods.append('Mount Pleasant')
        oakridge = self.request.GET.get('oakridge', None)
        if oakridge == 'true':
            neighbourhoods.append('Oakridge')
        south_cambie = self.request.GET.get('south_cambie', None)
        if south_cambie == 'true':
            neighbourhoods.append('South Cambie')
        renfrew_collingwood = self.request.GET.get('renfrew_collingwood', None)
        if renfrew_collingwood == 'true':
            neighbourhoods.append('Renfrew-Collingwood')
        riley_little_mountain = self.request.GET.get('riley_little_mountain', None)
        if riley_little_mountain == 'true':
            neighbourhoods.append('Riley-Little Mountain')
        shaughnessy = self.request.GET.get('shaughnessy', None)
        if shaughnessy == 'true':
            neighbourhoods.append('Shaughnessy')
        strathcona = self.request.GET.get('strathcona', None)
        if strathcona == 'true':
            neighbourhoods.append('Strathcona')
        sunset = self.request.GET.get('sunset', None)
        if sunset == 'true':
            neighbourhoods.append('Sunset')
        victoria_fraserview = self.request.GET.get('victoria_fraserview', None)
        if victoria_fraserview == 'true':
            neighbourhoods.append('Victoria-Fraserview')

        # Apply the filters
        if favorites:
            print(favorites)
            queryset = queryset.filter(park_id__in=favorites)
        if neighbourhoods:
            queryset = queryset.filter(neighbourhood__in=neighbourhoods)
        return queryset


def get_favorite_parks(request):
    favorite_parks = request.user.user_profile.favorite_park
    if favorite_parks is None:
        favorite_parks = [0]
        return favorite_parks
    else:
        list_favorite_parks = favorite_parks.split(',')
        list_favorite_parks = [s.replace(';','') for s in list_favorite_parks]
        list_favorite_parks = filter(None, list_favorite_parks)
        list_favorite_parks = list(map(int, list_favorite_parks))
        return list_favorite_parks


class DetailView(generic.DetailView):
    model = Park
    exclude = ('user',)
    template_name = 'parks/detail.html'
    slug_field = 'park_id'
    slug_url_kwarg = 'park_id'
    helmet = 'cool'


def get_data(request):
    if request.GET.get('getdata'):
        parse()
    return redirect('parks:index')


def clear_data(request):
    if request.GET.get('cleardata'):
        cleardb()
    return redirect('parks:index')


@csrf_exempt
def put_rating(request):

    if request.method == 'PUT':
        response_data = {}
        put = QueryDict(request.body)
        current_user = request.user
        if not current_user.is_authenticated():
            response_data['authenticated'] = False
            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )
        response_data['authenticated'] = True
        rating = put.get('rating')
        pid = put.get('pid')
        park = Park.objects.get(park_id=pid)
        park.update_rating(float(rating), current_user)


        response_data['park_id'] = park.park_id
        response_data['parkname'] = park.name
        response_data['rating'] = park.rating


        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse()

@login_required
def add_favorite_park(request, park_id):
    if request.method =='POST':
        user_profile = request.user.user_profile
        favorite_parks = request.user.user_profile.favorite_park
        if favorite_parks is None:
            favorite_parks = ''
        favorite_parks += ";"
        favorite_parks += park_id
        favorite_parks += ";,"
        user_profile.favorite_park = favorite_parks
        user_profile.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def unfavorite_park(request, park_id):
    if request.method =='POST':
        user_profile = request.user.user_profile
        favorite_parks = request.user.user_profile.favorite_park
        if favorite_parks is None:
            favorite_parks = ''
        deleted_park = ";"
        deleted_park += park_id
        deleted_park += ";,"
        new_favorite_parks = favorite_parks.replace(deleted_park, '')
        user_profile.favorite_park = new_favorite_parks
        user_profile.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def submit_problem(request, park_id):
    if request.POST:
        form = ProblemForm(request.POST)
        if form.is_valid():
            my_park = Park.objects.get(park_id=park_id)
            username = request.user.get_username()

parks/templates/parks/detail.html
{% include "parks/base.html" %}
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <title>{{ park.name }}</title>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static "css/portfolio-item.css" %}">
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <!-- CSS style -->
    <link rel="stylesheet" type="text/css" media="all" href="{% static "css/style.css" %}">

</head>

<body>

<!-- Facebook SDK -->
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '522365461271197',
            cookie     : true,
            xfbml      : true,
            version    : 'v2.5'

        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ park.name }}</h1> <h3><small>{{ park.neighbourhood }}</small></h3>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-6">
            {#                <img class="img-responsive" src="http://placehold.it/750x500" alt="">#}
            <img class="img-responsive" src="{{ park.image_url }}"/>
        </div>
        <div>
            <script>
                window.onload=function(){
                    var favorite_parks_list = '{{ request.user.user_profile.favorite_park }}';
                    var favorite_parks = favorite_parks_list.split(",");
                    if(favorite_parks.indexOf(';{{ park.park_id }};') >= 0) {
                        document.getElementById("favorite_form").style.display='none';
                    }
                    else {
                        document.getElementById("unfavorite_form").style.display='none';

                    }
                }
            </script>
            <div id="detail_btns">
                <form action="{% url 'parks:unfavorite' park.park_id %}" method="POST" id="unfavorite_form">
                             {% csrf_token %}
                    <input type="submit" class="btn" value="Unfavorite">
                </form>
                <script type="text/javascript">
                    $(document).ready(function(){
                            $('#unfavorite_form').on('submit', function (e) {
                            document.getElementById("favorite_form").style.display='block';
                            document.getElementById("unfavorite_form").style.display='none';
                        });
                    });
                </script>
                <form action="{% url 'parks:favorite' park.park_id %}" method="POST" id="favorite_form">
                    {% csrf_token %}
                    <input class="btn" type="submit" value="Favorite This Park">
                </form>
                &nbsp;&nbsp;&nbsp;
                <form>
                    <input type="button" class="btn" value="Check-In" name="check_in_button" id="check_in_button">
                </form>
                &nbsp;&nbsp;&nbsp;
                <form>
                    <input type="submit" class="btn" value="Share" name="share_button" id="share_button">
                </form>
            </div>
            <script type="text/javascript">
                $(document).ready(function(){
                    $('#favorite_form').on('submit', function (e) {
                        document.getElementById("favorite_form").style.display='none';
                        document.getElementById("unfavorite_form").style.display='block';
                    });
                });
            </script>
        </div>
            <div class="col-md-6">
                <em>Park ID: {{ park.park_id }}</em>
                <h4>Size: <small>{{ park.size }} Hectares</small></h4>
                <h4>Address: <small>{{ park.address }}</small></h4>
                <!-- <h4>Rating <small>{{ park.rating }}</small> </h4> -->
                <h4>Washrooms: <small>{% if park.washroom == 0 %}None{% else %}Yes{% endif %}</small> </h4>
                <h4>Official Park: <small>{% if park.official == 0 %}No{% else %}Yes{% endif %}</small></h4>
                <h4>Special: <small> {% if park.special == 0 %}No{% else %}Yes{% endif %} </small></h4>
                <h4>Advisory: <small>{% if park.advisory == 0 %}None{% else %}Yes{% endif %} </small></h4>

                <!-- RATING -->
                <p class="none" id="{{ park.park_id }}invrating">{{ park.rating }}</p>
                <div id="{{ park.park_id }}ratingcont" class="ratingcontainer">

                    <p id="start" class="none">{{ park.park_id }}</p>
                    <p class="ratingtext"></p>
                    <button id="half" action="/put_rating/" method="PUT" class="put-rating half one">

                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">0.5</p>


                    </button>

                    <button id="one" action="/put_rating/" method="PUT" class="put-rating full one">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">1</p>

                    </button>

                    <button id="onehalf" action="/put_rating/" method="PUT" class="put-rating half two">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">1.5</p>

                    </button>

                    <button id="two" action="/put_rating/" method="PUT" class="put-rating full two">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">2</p>

                    </button>

                    <button id="twohalf" action="/put_rating/" method="PUT" class="put-rating half three">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">2.5</p>

                    </button>

                    <button id="three" action="/put_rating/" method="PUT" class="put-rating full three">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">3</p>

                    </button>

                    <button id="threehalf" action="/put_rating/" method="PUT" class="put-rating half four">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">3.5</p>

                    </button>

                    <button id="four" action="/put_rating/" method="PUT" class="put-rating full four">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">4</p>

                    </button>

                    <button id="fourhalf" action="/put_rating/" method="PUT" class="put-rating half five">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">4.5</p>

                    </button>

                    <button id="five" action="/put_rating/" method="PUT" class="put-rating full five">
                        <p class="none">{{ park.park_id }}</p>
                        <p class="none">5</p>

                    </button>
                    <p class="none" id = "end"></p>
                </div> <br><br>


                <h4>Coordinates: <small>{{ park.lat }}, {{ park.long }}</small></h4>
                <h4><a href="{{ park.nurl }}"><small> Neighbourhood website </small></a></h4>
                <h4>Reported problems: <small>{{ park.problems }}</small></h4>
                {% if user.is_authenticated %}
                <h4>Did you notice a problem with the park? Please type a description of the problem here.</h4>
                <form action="{% url 'parks:problem' park.park_id %}" method="POST" id="problem-form">
                    {% csrf_token %}
                    <input type="text" maxlength="150" name="description">
                    <input class="btn" type="submit" value="Submit">
                </form>
                <script>
                    $(document).ready(function () {
                        $('#problem-form').on('submit', function (event) {
                            //event.preventDefault();
                            //var text = $('#problem').val();
                            var mytext = $("input[name='description']").val();
                            //submit_problem();
                        });
                    });
                </script>
            {% endif %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
    </div>
    <!-- /.row -->
    <div>

        <script type="text/javascript">
            $(document).ready(function(){
                $('#share_button').click(function(e){
                    e.preventDefault();
                    FB.ui({
                        method: 'feed',
                        link: '{{ park.nurl }}',
                        caption: 'Park',
                    }, function(response){
                    });
                });
            });
        </script>

        <script type="text/javascript">
            $(document).ready(function(){
                $('#check_in_button').click(function(e){
                    e.preventDefault();
                    FB.login(function(){
                        FB.api('/search', 'get',
                                {   q: '{{ park.name }}',
                                    type: 'place',
                                },
                                function (response){
                                    FB.api('/me/feed', 'post',
                                            {
                                                place: response.data[0].id,
                                            },
                                            function (response){
                                            }
                                    );
                                }
                        );
                    }, {scope: 'publish_actions'});
                });
            });
        </script>
    </div>
    <!-- Other Parks in Neighbourhood Row -->


    <!-- Portfolio Item Row -->
            <div class="col-lg-12">
                <h3 class="page-header">Nearby Parks </h3>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="{% url 'parks:detail' park.nearest1_id %}">
                    <img class="img-responsive portfolio-item" src="{{ park.nearest1_image }}"
                         alt="http://placehold.it/500x300"></a>
                <a href="{% url 'parks:detail' park.nearest1_id %}"><h4>{{ park.nearest1_name }}</h4></a>
                <h4><small><i>{{ park.nearest1_distance }} km away </i></small></h4>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="{% url 'parks:detail' park.nearest2_id %}">
                    <img class="img-responsive portfolio-item" src="{{ park.nearest2_image }}"
                         alt="http://placehold.it/500x300"></a>
                <a href="{% url 'parks:detail' park.nearest2_id %}"><h4>{{ park.nearest2_name }}</h4></a>
                <h4><small><i>{{ park.nearest2_distance }} km away </i></small></h4>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="{% url 'parks:detail' park.nearest3_id %}">
                    <img class="img-responsive portfolio-item" src="{{ park.nearest3_image }}"
                         alt="http://placehold.it/500x300"></a>
                <a href="{% url 'parks:detail' park.nearest3_id %}"><h4>{{ park.nearest3_name }}</h4></a>
                <h4><small><i>{{ park.nearest3_distance }} km away </i></small></h4>
            </div>

            <div class="col-sm-3 col-xs-6">
               <a href="{% url 'parks:detail' park.nearest4_id %}">
                    <img class="img-responsive portfolio-item" src="{{ park.nearest4_image }}"
                         alt="http://placehold.it/500x300"></a>
                <a href="{% url 'parks:detail' park.nearest4_id %}"><h4>{{ park.nearest4_name }}</h4></a>
                <h4><small><i>{{ park.nearest4_distance }} km away </i></small></h4>
            </div>
        </div>
    <!-- /.row -->

    <hr>

    <div
            class="fb-like"
            data-share="true"
            data-width="450"
            data-show-faces="true">
    </div>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; ParkTracker 2015</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
</body>

parks/templates/parks/problem_done.html
{% include "parks/base.html" %}
<title>Submit Successful</title>
<div style="margin-top:50px;">
    <p>Thank you for submitting a problem. The admins have been notified and will review the request.</p>
</div>